version: "3"

services:

  classifier:
    build: build/package
    container_name: classifier
    image: classifier
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      CLASSIFIER_FILE_PATH: "/data/classifier"
      WEB_SERVER_BIND_ADDR: ":80"
      WEB_SERVER_DEBUG: "1"
    volumes:
      - "/data"
    stop_grace_period: 5m